FROM node:lts-alpine3.15

WORKDIR /home/react-docker 

COPY package*.json .

ENV REACT_APP_URL=

RUN npm install

COPY . .

RUN npm i -g serve

RUN npm run build

EXPOSE 3000 

CMD ["serve", "-s", "build"] 